#Splash screen properties
#Wed Jul 08 21:13:41 CEST 2026
background=0x303030
bar=0xCB3D35
barBackground=0x252525
barBorder=0xC0C0C0
enabled=false
font=0x0
fontTexture=textures/font/ascii.png
forgeTexture=fml\:textures/gui/forge.gif
logoOffset=0
logoTexture=textures/gui/title/mojang.png
resourcePackPath=resources
rotate=false
